name: MSDO v1 self-hosted validation
on: push

permissions:
  id-token: write
  security-events: write

jobs:
  msdo-scan:
    name: MSDO v1 - Security Scan

    runs-on: self-hosted

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v6

    # Run MSDO v1
    - name: Run MSDO
      uses: ./
      id: msdo

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
