name: Microsoft Defender CLI v2 self-hosted validation
on: push

permissions:
  id-token: write
  security-events: write

jobs:
  defender-image-scan:
    name: Defender CLI v2 - Image Scan

    runs-on: self-hosted

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v6

    # Run Defender CLI v2 image scan
    - name: Run Defender CLI - Image Scan
      uses: ./
      id: defender
      with:
        command: 'image'
        imageName: 'ubuntu:latest'
        policy: 'mdc'
        break: 'false'
        pr-summary: 'true'

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: ${{ steps.defender.outputs.sarifFile }}

  defender-model-scan:
    name: Defender CLI v2 - Model Scan

    runs-on: self-hosted

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v6

    # Run Defender CLI v2 model scan
    - name: Run Defender CLI - Model Scan
      uses: ./
      id: defender
      with:
        command: 'model'
        modelPath: 'https://huggingface.co/Qwen/Qwen3.5-35B-A3B'
        policy: 'mdc'
        break: 'false'
        pr-summary: 'true'

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: ${{ steps.defender.outputs.sarifFile }}
