name: MSDO v1 self-hosted validation
on: push

permissions:
  id-token: write
  security-events: write

jobs:
  msdo-scan:
    name: MSDO v1 - Security Scan

    runs-on: self-hosted

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    # Run MSDO v1
    - name: Run MSDO
      uses: ./
      id: msdo

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@1190a975f95ce23525efb6a3fc21ea29567c1b52 # v3.38.2
      if: always()
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
