name: Build and Test

on:
  pull_request:
    branches:
      - main
      - 'release/**'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Compile Tests
      run: npm run buildTests

    - name: Run Tests
      run: npm test
